### PR TITLE
Adding PE support for versions 4 & 5

### PR DESCRIPTION
**Pull request by jcwarp**

### CODE REVIEW

**Comment by TJM** [comment]
Thanks @jcwarp ... We used your forked version. The *released* version doesn't work with the latest puppet (4.10.1), and we are also using PE, which you had a case for, so we didn't have to specify additional hieradata. Looks like tests are at odds with your fairly simple change, for some reason. :(

**Comment by jcwarp** [comment]
Wow, I made no changes to metadata.json... was I supposed to?
I do not understand the error output enough to try to fix it.

**Comment by TJM** [comment]
I don't think its possible that your little change to params.pp broke ALL those tests, there has to be something else wrong (Gemfile?).

**Comment by danieldreier** [comment]
@TJM and @jcwarp I really appreciate the work on this, and I'm sorry about the slow response. https://github.com/danieldreier/puppet-autosign/pull/21 was recently merged that addresses these problems, so I'm closing this.

**Pull request closed without merging**
