### PR TITLE
Numerous updates

### PR DESCRIPTION
**Pull request by treydock**
* Support EL7-EL9
* Support Puppet 7 and 8
* Support stdlib 9.x
* Use Voxpupuli Gemfile and some lint fixes

### CODE REVIEW

**Comment by the-yorkshire-allen** [comment]
@danieldreier Could you find some time to review treydock's changes?

**Review by danieldreier — APPROVED** [review]
I'm sorry for the slow review! Thank you for these improvements

**Comment by treydock** [comment]
@danieldreier Would you be willing for me to migrate this module to the Voxpupuli organization so this could be maintained by the community?  I pinged you on puppet-community Slack but figured you may not be active there.

**Comment by danieldreier** [comment]
Absolutely! I'd very much appreciate that

**Comment by the-yorkshire-allen** [comment]
Excellent - thanks for the effort people.

**Pull request merged**
